language: java
jdk: 
  - oraclejdk8
# services:
#   - mysql
addons:
  mariadb: '10.2'
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2       
before_install: 
  - cat ~travis/.my.cnf
  - ls .

sudo: true
before_script:
  - mysql -e 'SELECT @@version;'
  - USERDB='ISCuenta'
  - PASSWORD='Escom_17'
  # - mysql -e "GRANT ALL PRIVILEGES ON Biblioteca_Personas . * TO 'ISCuenta'@'localhost' IDENTIFIED BY 'Escom_17'";
  - mysql -u root < sql_scripts/DB_Biblioteca_Personas_CreateDB.sql
  - echo Base de datos creada.
  - mysql -u $USERDB -p$PASSWORD < sql_scripts/DB_Biblioteca_Personas_Catalogos.sql
  - echo Catalogos Inicializados.
  - mysql -u $USERDB -p$PASSWORD < sql_scripts/DB_Biblioteca_Personas_Extras.sql
  - echo Funciones extras agregadas.
  - mysql -u $USERDB -p$PASSWORD < sql_scripts/DB_Biblioteca_Personas_Personas.sql
  - echo Pruebas de Insercion realizadas.
  - mysql -e 'SELECT * FROM Biblioteca_Personas.Personas LIMIT 10'